### ISSUE TITLE
Let `make_laplace_threshold` work for integers

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1175]
From slack:

> Hi, does the make_base_laplace_threshold mechanism work only for float value?
> I was trying to implement it in this way
> ```
> mechanism = make_base_laplace_threshold(
>     map_domain(atom_domain(T=str), atom_domain(T=int)), l1_distance(T=int),
>     scale=1, threshold=10
> )
> ```
> but it works only when I change everything to float
> ```
> mechanism = make_base_laplace_threshold(
>     map_domain(atom_domain(T=str), atom_domain(T=float)), l1_distance(T=float),
>     scale=1., threshold=10.
> )
> ```
> Am I missing something or it just does not work for integers?

A:

> It doesn't work for integers. I agree that this is something that needs to be added. I have a good sense on how to add it, but proofs need to be written up first to ensure the details are correct.

**Comment by mccalluc** [comment]
Still an issue, although the function name has changed:
```
>>> m_int = dp.map_domain(dp.atom_domain(T=str), dp.atom_domain(T=int))
>>> dp.m.make_laplace_threshold(m_int, dp.l1_distance(T=int), scale=1, threshold=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/measurements.py", line 555, in make_laplace_threshold
    output = c_to_py(unwrap(lib_function(c_input_domain, c_input_metric, c_scale, c_threshold, c_k), Measurement))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_lib.py", line 254, in unwrap
    raise OpenDPException(variant, message, backtrace)
opendp.mod.OpenDPException:
  FFI("No match for concrete type i32. You've got a debug binary! Debug binaries support fewer types. Consult https://docs.opendp.org/en/stable/contributing/development-environment.html#build-opendp")
```

**Comment by Shoeboxam** [comment]
Integer laplace threshold is now implemented for Polars. The tail bound may be useful in a refactored thresholded laplace mechanism.
