### ISSUE TITLE
Context API Improvement: Better error message if epsilon or delta are not floats

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1471]
## Problem

- If `epsilon` is specified as an integer (`1`) instead of a float (`1.`, `1.0`, etc), then a type error is thrown.
- The same occurs for `delta`--an integer may not be a correct value for delta but the error should be more specific.

To replicate for `epsilon`, see below: `privacy_loss=dp.loss_of(epsilon=1, delta=1e-6),`

Similar replication may be done for the `delta` value

```Python
>>> import opendp.prelude as dp
>>> dp.enable_features("contrib")
>>> 
>>> 
>>> dp.Context.compositor(
...     data=[1] * 100,
...     privacy_unit=dp.unit_of(contributions=1),
...     privacy_loss=dp.loss_of(epsilon=1, delta=1e-6),
...     split_evenly_over=1
... )
Traceback (most recent call last):
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/mod.py", line 1048, in exponential_bounds_search
    predicate(center)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/mod.py", line 828, in <lambda>
    return binary_search(lambda param: make_chain(param).check(d_in, d_out), bounds, T)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/context.py", line 727, in scale_sc
    return make_sequential_composition(
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/combinators.py", line 370, in make_sequential_composition
    c_d_mids = py_to_c(d_mids, c_type=AnyObjectPtr, type_name=RuntimeType(origin='Vec', args=[QO]))
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 112, in py_to_c
    return slice_as_object(value, type_name) # type: ignore
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_data.py", line 230, in slice_as_object
    c_raw = py_to_c(raw, c_type=FfiSlicePtr, type_name=T)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 117, in py_to_c
    return _py_to_slice(value, RuntimeType.parse(type_name))
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 234, in _py_to_slice
    return _vector_to_slice(value, type_name)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 304, in _vector_to_slice
    c_repr = [py_to_c(v, c_type=AnyObjectPtr, type_name=inner_type_name) for v in val]
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 304, in <listcomp>
    c_repr = [py_to_c(v, c_type=AnyObjectPtr, type_name=inner_type_name) for v in val]
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 112, in py_to_c
    return slice_as_object(value, type_name) # type: ignore
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_data.py", line 230, in slice_as_object
    c_raw = py_to_c(raw, c_type=FfiSlicePtr, type_name=T)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 117, in py_to_c
    return _py_to_slice(value, RuntimeType.parse(type_name))
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 240, in _py_to_slice
    return _tuple_to_slice(value, type_name)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 382, in _tuple_to_slice
    check_similar_scalar(inner_type_name, v)
  File "/Users/ramanprasad/Documents/github-rp/opendp/python/src/opendp/_convert.py", line 45, in check_similar_scalar
    raise TypeError(f"inferred type is {inferred}, expected {expected}. See {_ERROR_URL_298}")
TypeError: inferred type is f64, expected i32. See https://github.com/opendp/opendp/discussions/298
```

## Possible Resolutions

- Specific error messaging or cast the `epsilon`/`delta` params floats.
  - Note, if `delta` is cast to a float, it will give an error message for the expected `delta` range

**Comment by Shoeboxam** [comment]
Could we resolve this at the root with #943?

**Comment by Shoeboxam** [comment]
Closed in #943
