### ISSUE TITLE
Usability with debug binary? `make_randomized_response` with numbers

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1552]
Strings work:
```
>>> random_string = dp.m.make_randomized_response(['a', 'b', 'c'], 0.99)
>>> random_string('a')
a
```
but numbers don't:
```
>>> randomized_response = dp.m.make_randomized_response([1.0, 2.0, 3.0], 0.99)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/measurements.py", line 709, in make_randomized_response
    output = c_to_py(unwrap(lib_function(c_categories, c_prob, c_constant_time, c_T, c_QO), Measurement))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_lib.py", line 270, in unwrap
    raise OpenDPException(variant, message, backtrace)
opendp.mod.OpenDPException:
  FFI("No match for concrete type f64. You've got a debug binary! Debug binaries support fewer types. Consult https://docs.opendp.org/en/stable/contributor/development-environment.html#build-opendp")
```
```
>>> randomized_response = dp.m.make_randomized_response([1, 2, 3], 0.99)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/measurements.py", line 709, in make_randomized_response
    output = c_to_py(unwrap(lib_function(c_categories, c_prob, c_constant_time, c_T, c_QO), Measurement))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_lib.py", line 270, in unwrap
    raise OpenDPException(variant, message, backtrace)
opendp.mod.OpenDPException:
  FFI("No match for concrete type i32. You've got a debug binary! Debug binaries support fewer types. Consult https://docs.opendp.org/en/stable/contributor/development-environment.html#build-opendp")
```
Am I doing something wrong?

**Comment by raprasad** [comment]
only takes string b/c _debug_ binary only allows strings. release build has all the types

**Comment by mccalluc** [comment]
This would make the dev build a lot slower, so this is fine as is. If Polars does more of the lifting, we can get rid of code, but leave as is for now.

**Comment by raprasad** [comment]
(Using a "debug" binary only takes strings. Release builds have all types)
