### ISSUE TITLE
Usability: Cast Polars DataFrame to LazyFrame?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1583]
Note: There are at least two different places where dataframes instead of lazyframes can cause problems. Look farther down the thread.

----------------

If by mistake you pass a `DataFrame` instead of a `LazyFrame` to the measurment we get from `make_private_lazyframe`, the error isn't too helpful, and the stacktrace is long

<details>

```
Traceback (most recent call last):
  File "/tmp/make_private_lazyframe.py", line 43, in <module>
    results = dp_sum_pets_by_grade(df).sort("grade").collect()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/mod.py", line 74, in __call__
    return measurement_invoke(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/core.py", line 363, in measurement_invoke
    c_arg = py_to_c(arg, c_type=AnyObjectPtr, type_name=measurement_input_carrier_type(this))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_convert.py", line 111, in py_to_c
    return slice_as_object(value, type_name) # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_data.py", line 275, in slice_as_object
    c_raw = py_to_c(raw, c_type=FfiSlicePtr, type_name=T)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_convert.py", line 116, in py_to_c
    return _py_to_slice(value, RuntimeType.parse(type_name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_convert.py", line 247, in _py_to_slice
    return _lazyframe_to_slice(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_convert.py", line 479, in _lazyframe_to_slice
    raw = _wrap_in_slice(state, len(state))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/opendp/python/src/opendp/_convert.py", line 560, in _wrap_in_slice
    return FfiSlicePtr(FfiSlice(ctypes.cast(ptr, ctypes.c_void_p), len_))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 512, in cast
    return _cast(obj, obj, typ)
           ^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 1: TypeError: wrong type
```

</details>

My guess is that the change would need to happen on the rust side rather than the python, so this might be tricky.

**Comment by Shoeboxam** [comment]
I think this error can be handled from Python, specifically in `_lazyframe_to_slice`

**Comment by mccalluc** [comment]
Slightly different manifestation of the same problem, but instead of using a dataframe in a measurement, it's being used to define a Context. This doesn't include `_lazyframe_to_slice` in the stacktrace.

I'm getting this error:
```
...
  File "/Users/chuckmccallum/github/opendp/dp-creator-ii/dp_creator_ii/app/components/column_module.py", line 82, in column_plot
    context = dp.Context.compositor(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/dp-creator-ii/.venv/lib/python3.12/site-packages/opendp/context.py", line 398, in compositor
    domain = domain_of(data, infer=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chuckmccallum/github/opendp/dp-creator-ii/.venv/lib/python3.12/site-packages/opendp/context.py", line 201, in domain_of
    raise TypeError(f"unrecognized carrier type: {T}")
TypeError: unrecognized carrier type: DataFrame
```

This fixes it:
```diff
        context = dp.Context.compositor(
-            data=df.with_columns(
+            data=pl.LazyFrame(df).with_columns(
```

**Comment by Shoeboxam** [comment]
I don't think we want to auto-coerce dataframes to lazyframes, as I anticipate us using dataframe domains at some point directly. The approach would be more like, no error is raised, but you call `context.query().lazy().select(...)`, which desugars to a call to `make_lazy`, a stable transformation from a dataframe to a lazyframe.
