### ISSUE TITLE
PyPi OpenDP 0.10.0 on Windows Install Problem

### ISSUE THREAD

**Issue by joshua-oss** [opendp/opendp#1758]
`pip install opendp` into a fresh Conda environment succeeds, but attempting to import the library throws exception: "Expected exactly one binary to be present".

**To Reproduce** (device is Intel x64)
1. conda create env --name windp
2. conda activate windp
3. conda install pip
4. pip install opendp
5. python
6. >> from opendp.transformations import make_sum, make_clamp

**Result**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\joshuaa\AppData\Local\miniconda3\envs\windp\Lib\site-packages\opendp\__init__.py", line 1, in <module>
    from opendp.mod import Transformation, Measurement, OpenDPException, UnknownTypeException
  File "C:\Users\joshuaa\AppData\Local\miniconda3\envs\windp\Lib\site-packages\opendp\mod.py", line 13, in <module>
    from opendp._lib import AnyMeasurement, AnyTransformation, AnyDomain, AnyMetric, AnyMeasure, AnyFunction
  File "C:\Users\joshuaa\AppData\Local\miniconda3\envs\windp\Lib\site-packages\opendp\_lib.py", line 46, in <module>
    lib, lib_path = _load_library()
                    ^^^^^^^^^^^^^^^
  File "C:\Users\joshuaa\AppData\Local\miniconda3\envs\windp\Lib\site-packages\opendp\_lib.py", line 31, in _load_library
    raise Exception(f"Expected exactly one binary to be present. Got: {lib_dir_file_names}")
Exception: Expected exactly one binary to be present. Got: []

**Comment by mccalluc** [comment]
@joshua-oss, thank you for the bug report. I'm realizing we auto-closed this issue when the fix was merged to main, but we neglected to post instructions here for using the nightly build. We are now preparing the release 0.11 release which will include the fix.

Until that is out, `pip install opendp==0.10.0a20240804001` should work properly.
