### ISSUE TITLE
Downcast of IsVec/Column Failing

### ISSUE THREAD

**Issue by r-fndv** [opendp/opendp#667]
Hi everyone,

I have been working on implementing a `SizedDataFrameDomain` under Mike's guidance. On the way, I stumbled up on the following difficulty when using the `Column` struct `as_form`function:  down-casting a Column's content from a dataframe has been failing.

Here is the code I am using to generate the bug (I run it as a test in `rust/src/data/mod.rs`). The error orginated from `Column.as_form()`but also applies `IsVec`'s `downcast_ref`:

```
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vec() {
        let form = vec![1, 2, 3];
        test_round_trip(form);

        use crate::{transformations::make_create_dataframe};

        fn print_type_of<T>(_: &T) {
            println!("{}", std::any::type_name::<T>())
        }

        let transformation = make_create_dataframe::<&str>(vec!["colA", "colB"]).unwrap();

        let data_string = vec![
            vec!["1".to_owned(), "A".to_owned()],
            vec!["4".to_owned(), "A".to_owned()],
            vec!["2".to_owned(), "B".to_owned()],
            vec!["0".to_owned(), "A".to_owned()],
            vec!["10".to_owned(), "B".to_owned()],
        ];
        
        let df = transformation.invoke(&data_string).unwrap();

        let records = vec!["A","A","B","A","B"];

        let data = Column(Box::new(records));
        println!("{:?}", data);
        
        let col = df.get("colB").unwrap_test()
                .to_owned();
        println!("{:?}", col);


        let tmp = data.0.box_clone();
        print_type_of(&tmp);
        let tmp: &Vec<&str> = tmp.as_any().downcast_ref().unwrap_test();
        print_type_of(&tmp);
        println!("{:?}", tmp);
        
        let tmp2 = col.0.box_clone();
        print_type_of(&tmp2);
        let tmp2: &Vec<&str> = tmp2.as_any().downcast_ref().unwrap_test();
        print_type_of(&tmp2);
        println!("{:?}", tmp2);

        let cat = col        
                .as_form::<Vec<&str>>()
                .unwrap_test();
        assert_eq!(data, col);

        println!("{:?}", cat);

    }

    // #[test]
    // #[should_panic]
    // fn test_bogus() {
    //     let form = (Data::new(vec![1, 2, 3]), Data::new(99.9));
    //     let data = Data::new(form);
    //     let _retrieved: Vec<String> = data.into_form();
    // }

    fn test_round_trip<T: 'static + IsVec + PartialEq>(form: T) {
        let data = Column(form.box_clone());
        assert_eq!(&form, data.as_form().unwrap_test());
        assert_eq!(form, data.into_form().unwrap_test())
    }
}

```
which gives the following error:
```
running 1 test
Column(["A", "A", "B", "A", "B"])
Column(["A", "A", "B", "A", "B"])
alloc::boxed::Box<dyn opendp::data::IsVec>
&alloc::vec::Vec<&str>
["A", "A", "B", "A", "B"]
alloc::boxed::Box<dyn opendp::data::IsVec>
thread 'data::tests::test_vec' panicked at 'called `Option::unwrap()` on a `None` value', src/data/mod.rs:155:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:778:21
   4: opendp::data::tests::test_vec
             at ./src/data/mod.rs:155:32
   5: opendp::data::tests::test_vec::{{closure}}
             at ./src/data/mod.rs:115:19
   6: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test data::tests::test_vec ... FAILED
```

I am having a hard time figuring out if I am doing something wrong (I am a Rust beginner) or if there is indeed an issue with the current downcasting of Columns/IsVec. Surprisingly it seems to work fine in `make_select_column`. 

Any pointer / help would be very helpful, many thanks in advance!

**Comment by raprasad** [comment]
Closing. Will be solved when Polars is fully implemented in #695 . (cc: @r-fndv)
